name: Deploy to Github Page

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          npm install -g gh-pages
          gh-pages -d build
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TO_GITHUB_PAGE }}
          REPOSITORY: ${{ github.repository }}
